[workspace]
members = [
    "bronze",
    "bronze/bronzeflow-utils",
    "bronze/bronzeflow-time",
    "bronze/bronzeflow-core"
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
cron = "0.12.0"
chrono = "0.4.22"
anyhow = "1.0.55"

futures = "0.3.25"
