name: Build and test Rust

on:
  pull_request:
    paths:
      - 'bronze/**'
      - '.github/workflows/build-test-rust.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-11-03

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        working-directory: ./bronze/examples
        run: cargo check

  features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-11-03

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: cargo install cargo-hack

      - name: Run cargo hack
        working-directory: bronze
        run: cargo hack check --each-feature --no-dev-deps

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bronze

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-11-03
          components: rustfmt, clippy

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: bronze

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run : |
          cargo clippy --all-targets --all-features --tests --benches -- -D warnings

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: bronze

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-11-03

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: bronze

      - name: Run tests
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: make test

      - name: Run integration tests
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: make integration-tests
